name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install latex
        run: sudo apt-get install -y texlive texlive-xetex texlive-fonts-extra latexmk
      - name: Compile LaTeX document
        run: make build
