name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install latex
        run: apt-get install -y latexmk
      - name: Compile LaTeX document
        run: latexmk -xelatex FieldGuide.tex
